name: Github Action test
on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

      - name: "Say Hello Mona it's Tuesday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Meenu
  jobs:
    job2:
      runs-on: ubuntu-latest
      steps:
          - name: "name please"
            run: echo "Today is $DAY_OF_WEEK!"
