name: Githubref
on: 
  workflow_dispatch:

jobs:
  refer:
    runs-on: ubuntu-latest
    steps:      
      - name: Branch name
        run: |
          echo "BRANCH_TAG=$(echo $GITHUB_REF_NAME )" >> $GITHUB_ENV 
          
      - name: Branchshow
        run: |
          echo ${{ env.BRANCH_TAG }} 

