      - name: Branch name
        run: |
          echo "BRANCH_TAG=$(echo $GITHUB_REF_NAME )" >> $GITHUB_ENV `
          echo "BRANCH_NAME=$(echo $GITHUB_REF )" >> $GITHUB_ENV
      - name: Branch-name-show
        run: |
          echo ${{ env.BRANCH_TAG }} `
          echo ${{ env.BRANCH_NAME }}
