on:
  push:
    branches:
      - main

name: Add tags

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Apply tags
        id: apply-tags
        shell: pwsh
        run: |
          ./tag.ps1
