on:
  push:
    branches:
      - main
      - develop



name: Deploy Tag
jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Apply tags to main
        id: apply-tags-main
        shell: pwsh
        if: github.ref == 'refs/heads/main'     
        run: |
          echo "running version_tag_main"
          ./tag.ps1 `
            -tagPrefix "release"
      - name: Apply tags to develop
        id: apply-tags-develop
        shell: pwsh
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "running version_tag_develop"
          ./tag.ps1 `
            -tagPrefix "develop"
        
