on:
  push:
    branches:
      - main
      - break
    

name: Add tags

jobs:
  apply-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Apply tags
        id: apply-tags
        if: github.ref == 'refs/heads/break'
        shell: pwsh        
        run: |
          echo "running tag"
          ./tag.ps1 `
            - tagPrefix "break_"
        
        
        
